<a href="https://colab.research.google.com/github/Mo3goprav/innopolis/blob/main/Levin_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

n = 4 #количество стобцов
k = 5 #количество строк
m = n*k
mx = np.empty(m)

for i in range(m): #цикл для расчет чисел фибоначи
  if i == 0:
    mx[i] = 0
  elif i == 1:
    mx[i] = 1
  else:
    mx[i] = mx[i-1] + mx[i-2]

mx = np.reshape(mx, (n,k)) #создание матрицы

print(mx)

[[0.000e+00 1.000e+00 1.000e+00 2.000e+00 3.000e+00]
 [5.000e+00 8.000e+00 1.300e+01 2.100e+01 3.400e+01]
 [5.500e+01 8.900e+01 1.440e+02 2.330e+02 3.770e+02]
 [6.100e+02 9.870e+02 1.597e+03 2.584e+03 4.181e+03]]


In [ ]:
# вывод списков по запросу
print(f'Cумма по столбцам {np.sum(mx, axis=0)} \nCумма по строкам {np.sum(mx, axis=1)} \nМаксимальное по столбцам {np.max(mx, axis=0)} \nМаксимальное по строкам {np.max(mx, axis=1)} \nМинимальное по столбцам {np.min(mx, axis=0)} \nМинимальное по строкам {np.min(mx, axis=1)} \n')

Cумма по столбцам [ 670. 1085. 1755. 2840. 4595.] 
Cумма по строкам [7.000e+00 8.100e+01 8.980e+02 9.959e+03] 
Максимальное по столбцам [ 610.  987. 1597. 2584. 4181.] 
Максимальное по строкам [3.000e+00 3.400e+01 3.770e+02 4.181e+03] 
Минимальное по столбцам [0. 1. 1. 2. 3.] 
Минимальное по строкам [  0.   5.  55. 610.] 



In [ ]:
for i in range(n): #цикл который проходит по всем значениям матрицы и те которые больше 500 заменяет на 1
  for j in range(k):
    if mx[i][j] > 500:
      mx[i][j] = 1

print(mx)

[[  0.   1.   1.   2.   3.]
 [  5.   8.  13.  21.  34.]
 [ 55.  89. 144. 233. 377.]
 [  1.   1.   1.   1.   1.]]
